package alignment

import "github.com/ggeorgiev/instant-chess/src/square"

type Relation uint
type Relations [square.Number][square.Number]Relation

const (
	NotAligned Relation = iota
	SameSquare
	FileAbove
	FileUnder
	RankLeft
	RankRight
	DiagonalAbove
	DiagonalUnder
	CounterDiagonalAbove
	CounterDiagonalUnder
)

const (
	na = NotAligned
	ss = SameSquare
	fa = FileAbove
	fu = FileUnder
	rl = RankLeft
	rr = RankRight
	da = DiagonalAbove
	du = DiagonalUnder
	ca = CounterDiagonalAbove
	cu = CounterDiagonalUnder
)

var SquareRelations = Relations{
	{
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
		fa, na, na, da, na, na, na, na,
		fa, na, na, na, da, na, na, na,
		fa, na, na, na, na, da, na, na,
		fa, na, na, na, na, na, da, na,
		fa, na, na, na, na, na, na, da,
	},
	{
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
		na, fa, na, na, da, na, na, na,
		na, fa, na, na, na, da, na, na,
		na, fa, na, na, na, na, da, na,
		na, fa, na, na, na, na, na, da,
		na, fa, na, na, na, na, na, na,
	},
	{
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
		na, na, fa, na, na, da, na, na,
		na, na, fa, na, na, na, da, na,
		na, na, fa, na, na, na, na, da,
		na, na, fa, na, na, na, na, na,
		na, na, fa, na, na, na, na, na,
	},
	{
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
		ca, na, na, fa, na, na, da, na,
		na, na, na, fa, na, na, na, da,
		na, na, na, fa, na, na, na, na,
		na, na, na, fa, na, na, na, na,
		na, na, na, fa, na, na, na, na,
	},
	{
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
		na, ca, na, na, fa, na, na, da,
		ca, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
	},
	{
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
		na, na, ca, na, na, fa, na, na,
		na, ca, na, na, na, fa, na, na,
		ca, na, na, na, na, fa, na, na,
		na, na, na, na, na, fa, na, na,
		na, na, na, na, na, fa, na, na,
	},
	{
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
		na, na, na, ca, na, na, fa, na,
		na, na, ca, na, na, na, fa, na,
		na, ca, na, na, na, na, fa, na,
		ca, na, na, na, na, na, fa, na,
		na, na, na, na, na, na, fa, na,
	},
	{
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
		na, na, na, na, ca, na, na, fa,
		na, na, na, ca, na, na, na, fa,
		na, na, ca, na, na, na, na, fa,
		na, ca, na, na, na, na, na, fa,
		ca, na, na, na, na, na, na, fa,
	},
	{
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
		fa, na, na, da, na, na, na, na,
		fa, na, na, na, da, na, na, na,
		fa, na, na, na, na, da, na, na,
		fa, na, na, na, na, na, da, na,
	},
	{
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
		na, fa, na, na, da, na, na, na,
		na, fa, na, na, na, da, na, na,
		na, fa, na, na, na, na, da, na,
		na, fa, na, na, na, na, na, da,
	},
	{
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
		na, na, fa, na, na, da, na, na,
		na, na, fa, na, na, na, da, na,
		na, na, fa, na, na, na, na, da,
		na, na, fa, na, na, na, na, na,
	},
	{
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
		ca, na, na, fa, na, na, da, na,
		na, na, na, fa, na, na, na, da,
		na, na, na, fa, na, na, na, na,
		na, na, na, fa, na, na, na, na,
	},
	{
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
		na, ca, na, na, fa, na, na, da,
		ca, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
	},
	{
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
		na, na, ca, na, na, fa, na, na,
		na, ca, na, na, na, fa, na, na,
		ca, na, na, na, na, fa, na, na,
		na, na, na, na, na, fa, na, na,
	},
	{
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
		na, na, na, ca, na, na, fa, na,
		na, na, ca, na, na, na, fa, na,
		na, ca, na, na, na, na, fa, na,
		ca, na, na, na, na, na, fa, na,
	},
	{
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
		na, na, na, na, ca, na, na, fa,
		na, na, na, ca, na, na, na, fa,
		na, na, ca, na, na, na, na, fa,
		na, ca, na, na, na, na, na, fa,
	},
	{
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
		fa, na, na, da, na, na, na, na,
		fa, na, na, na, da, na, na, na,
		fa, na, na, na, na, da, na, na,
	},
	{
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
		na, fa, na, na, da, na, na, na,
		na, fa, na, na, na, da, na, na,
		na, fa, na, na, na, na, da, na,
	},
	{
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
		na, na, fa, na, na, da, na, na,
		na, na, fa, na, na, na, da, na,
		na, na, fa, na, na, na, na, da,
	},
	{
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
		ca, na, na, fa, na, na, da, na,
		na, na, na, fa, na, na, na, da,
		na, na, na, fa, na, na, na, na,
	},
	{
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
		na, ca, na, na, fa, na, na, da,
		ca, na, na, na, fa, na, na, na,
		na, na, na, na, fa, na, na, na,
	},
	{
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
		na, na, ca, na, na, fa, na, na,
		na, ca, na, na, na, fa, na, na,
		ca, na, na, na, na, fa, na, na,
	},
	{
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
		na, na, na, ca, na, na, fa, na,
		na, na, ca, na, na, na, fa, na,
		na, ca, na, na, na, na, fa, na,
	},
	{
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
		na, na, na, na, ca, na, na, fa,
		na, na, na, ca, na, na, na, fa,
		na, na, ca, na, na, na, na, fa,
	},
	{
		fu, na, na, cu, na, na, na, na,
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
		fa, na, na, da, na, na, na, na,
		fa, na, na, na, da, na, na, na,
	},
	{
		na, fu, na, na, cu, na, na, na,
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
		na, fa, na, na, da, na, na, na,
		na, fa, na, na, na, da, na, na,
	},
	{
		na, na, fu, na, na, cu, na, na,
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
		na, na, fa, na, na, da, na, na,
		na, na, fa, na, na, na, da, na,
	},
	{
		du, na, na, fu, na, na, cu, na,
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
		ca, na, na, fa, na, na, da, na,
		na, na, na, fa, na, na, na, da,
	},
	{
		na, du, na, na, fu, na, na, cu,
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
		na, ca, na, na, fa, na, na, da,
		ca, na, na, na, fa, na, na, na,
	},
	{
		na, na, du, na, na, fu, na, na,
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
		na, na, ca, na, na, fa, na, na,
		na, ca, na, na, na, fa, na, na,
	},
	{
		na, na, na, du, na, na, fu, na,
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
		na, na, na, ca, na, na, fa, na,
		na, na, ca, na, na, na, fa, na,
	},
	{
		na, na, na, na, du, na, na, fu,
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
		na, na, na, na, ca, na, na, fa,
		na, na, na, ca, na, na, na, fa,
	},
	{
		fu, na, na, na, cu, na, na, na,
		fu, na, na, cu, na, na, na, na,
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
		fa, na, na, da, na, na, na, na,
	},
	{
		na, fu, na, na, na, cu, na, na,
		na, fu, na, na, cu, na, na, na,
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
		na, fa, na, na, da, na, na, na,
	},
	{
		na, na, fu, na, na, na, cu, na,
		na, na, fu, na, na, cu, na, na,
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
		na, na, fa, na, na, da, na, na,
	},
	{
		na, na, na, fu, na, na, na, cu,
		du, na, na, fu, na, na, cu, na,
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
		ca, na, na, fa, na, na, da, na,
	},
	{
		du, na, na, na, fu, na, na, na,
		na, du, na, na, fu, na, na, cu,
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
		na, ca, na, na, fa, na, na, da,
	},
	{
		na, du, na, na, na, fu, na, na,
		na, na, du, na, na, fu, na, na,
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
		na, na, ca, na, na, fa, na, na,
	},
	{
		na, na, du, na, na, na, fu, na,
		na, na, na, du, na, na, fu, na,
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
		na, na, na, ca, na, na, fa, na,
	},
	{
		na, na, na, du, na, na, na, fu,
		na, na, na, na, du, na, na, fu,
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
		na, na, na, na, ca, na, na, fa,
	},
	{
		fu, na, na, na, na, cu, na, na,
		fu, na, na, na, cu, na, na, na,
		fu, na, na, cu, na, na, na, na,
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
		fa, na, da, na, na, na, na, na,
	},
	{
		na, fu, na, na, na, na, cu, na,
		na, fu, na, na, na, cu, na, na,
		na, fu, na, na, cu, na, na, na,
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
		na, fa, na, da, na, na, na, na,
	},
	{
		na, na, fu, na, na, na, na, cu,
		na, na, fu, na, na, na, cu, na,
		na, na, fu, na, na, cu, na, na,
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
		ca, na, fa, na, da, na, na, na,
	},
	{
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, cu,
		du, na, na, fu, na, na, cu, na,
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
		na, ca, na, fa, na, da, na, na,
	},
	{
		na, na, na, na, fu, na, na, na,
		du, na, na, na, fu, na, na, na,
		na, du, na, na, fu, na, na, cu,
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
		na, na, ca, na, fa, na, da, na,
	},
	{
		du, na, na, na, na, fu, na, na,
		na, du, na, na, na, fu, na, na,
		na, na, du, na, na, fu, na, na,
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
		na, na, na, ca, na, fa, na, da,
	},
	{
		na, du, na, na, na, na, fu, na,
		na, na, du, na, na, na, fu, na,
		na, na, na, du, na, na, fu, na,
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
		na, na, na, na, ca, na, fa, na,
	},
	{
		na, na, du, na, na, na, na, fu,
		na, na, na, du, na, na, na, fu,
		na, na, na, na, du, na, na, fu,
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
		na, na, na, na, na, ca, na, fa,
	},
	{
		fu, na, na, na, na, na, cu, na,
		fu, na, na, na, na, cu, na, na,
		fu, na, na, na, cu, na, na, na,
		fu, na, na, cu, na, na, na, na,
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
		fa, da, na, na, na, na, na, na,
	},
	{
		na, fu, na, na, na, na, na, cu,
		na, fu, na, na, na, na, cu, na,
		na, fu, na, na, na, cu, na, na,
		na, fu, na, na, cu, na, na, na,
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
		ca, fa, da, na, na, na, na, na,
	},
	{
		na, na, fu, na, na, na, na, na,
		na, na, fu, na, na, na, na, cu,
		na, na, fu, na, na, na, cu, na,
		na, na, fu, na, na, cu, na, na,
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
		na, ca, fa, da, na, na, na, na,
	},
	{
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, cu,
		du, na, na, fu, na, na, cu, na,
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
		na, na, ca, fa, da, na, na, na,
	},
	{
		na, na, na, na, fu, na, na, na,
		na, na, na, na, fu, na, na, na,
		du, na, na, na, fu, na, na, na,
		na, du, na, na, fu, na, na, cu,
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
		na, na, na, ca, fa, da, na, na,
	},
	{
		na, na, na, na, na, fu, na, na,
		du, na, na, na, na, fu, na, na,
		na, du, na, na, na, fu, na, na,
		na, na, du, na, na, fu, na, na,
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
		na, na, na, na, ca, fa, da, na,
	},
	{
		du, na, na, na, na, na, fu, na,
		na, du, na, na, na, na, fu, na,
		na, na, du, na, na, na, fu, na,
		na, na, na, du, na, na, fu, na,
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
		na, na, na, na, na, ca, fa, da,
	},
	{
		na, du, na, na, na, na, na, fu,
		na, na, du, na, na, na, na, fu,
		na, na, na, du, na, na, na, fu,
		na, na, na, na, du, na, na, fu,
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
		na, na, na, na, na, na, ca, fa,
	},
	{
		fu, na, na, na, na, na, na, cu,
		fu, na, na, na, na, na, cu, na,
		fu, na, na, na, na, cu, na, na,
		fu, na, na, na, cu, na, na, na,
		fu, na, na, cu, na, na, na, na,
		fu, na, cu, na, na, na, na, na,
		fu, cu, na, na, na, na, na, na,
		ss, rr, rr, rr, rr, rr, rr, rr,
	},
	{
		na, fu, na, na, na, na, na, na,
		na, fu, na, na, na, na, na, cu,
		na, fu, na, na, na, na, cu, na,
		na, fu, na, na, na, cu, na, na,
		na, fu, na, na, cu, na, na, na,
		na, fu, na, cu, na, na, na, na,
		du, fu, cu, na, na, na, na, na,
		rl, ss, rr, rr, rr, rr, rr, rr,
	},
	{
		na, na, fu, na, na, na, na, na,
		na, na, fu, na, na, na, na, na,
		na, na, fu, na, na, na, na, cu,
		na, na, fu, na, na, na, cu, na,
		na, na, fu, na, na, cu, na, na,
		du, na, fu, na, cu, na, na, na,
		na, du, fu, cu, na, na, na, na,
		rl, rl, ss, rr, rr, rr, rr, rr,
	},
	{
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, na,
		na, na, na, fu, na, na, na, cu,
		du, na, na, fu, na, na, cu, na,
		na, du, na, fu, na, cu, na, na,
		na, na, du, fu, cu, na, na, na,
		rl, rl, rl, ss, rr, rr, rr, rr,
	},
	{
		na, na, na, na, fu, na, na, na,
		na, na, na, na, fu, na, na, na,
		na, na, na, na, fu, na, na, na,
		du, na, na, na, fu, na, na, na,
		na, du, na, na, fu, na, na, cu,
		na, na, du, na, fu, na, cu, na,
		na, na, na, du, fu, cu, na, na,
		rl, rl, rl, rl, ss, rr, rr, rr,
	},
	{
		na, na, na, na, na, fu, na, na,
		na, na, na, na, na, fu, na, na,
		du, na, na, na, na, fu, na, na,
		na, du, na, na, na, fu, na, na,
		na, na, du, na, na, fu, na, na,
		na, na, na, du, na, fu, na, cu,
		na, na, na, na, du, fu, cu, na,
		rl, rl, rl, rl, rl, ss, rr, rr,
	},
	{
		na, na, na, na, na, na, fu, na,
		du, na, na, na, na, na, fu, na,
		na, du, na, na, na, na, fu, na,
		na, na, du, na, na, na, fu, na,
		na, na, na, du, na, na, fu, na,
		na, na, na, na, du, na, fu, na,
		na, na, na, na, na, du, fu, cu,
		rl, rl, rl, rl, rl, rl, ss, rr,
	},
	{
		du, na, na, na, na, na, na, fu,
		na, du, na, na, na, na, na, fu,
		na, na, du, na, na, na, na, fu,
		na, na, na, du, na, na, na, fu,
		na, na, na, na, du, na, na, fu,
		na, na, na, na, na, du, na, fu,
		na, na, na, na, na, na, du, fu,
		rl, rl, rl, rl, rl, rl, rl, ss,
	},
}
